saveicon=document.getElementById("save")
loadicon=document.getElementById("load")

let savesound= new Audio("Audio/correct-2-46134.mp3");
let loadsound= new Audio("Audio/click-button-140881.mp3");

if(localStorage.getItem("volume")!=null){
    sliderVolume.value=localStorage.getItem("volume")
}
if(localStorage.getItem("workminute")!=null){
    Workminute.value=localStorage.getItem("workminute")
    Workminute.onchange()
}
if(localStorage.getItem("worksecond")!=null){
    Worksecond.value=localStorage.getItem("worksecond")
    Worksecond.onchange()
}
if(localStorage.getItem("sbminute")!=null){
    SBreakminute.value=localStorage.getItem("sbminute")
    SBreakminute.onchange()
}
if(localStorage.getItem("sbsecond")!=null){
    SBreaksecond.value=localStorage.getItem("sbsecond")
    SBreaksecond.onchange()
}
if(localStorage.getItem("lbminute")!=null){
    LBreakminute.value=localStorage.getItem("lbminute")
    LBreakminute.onchange()
}
if(localStorage.getItem("lbsecond")!=null){
    LBreaksecond.value=localStorage.getItem("lbsecond")
    LBreaksecond.onchange()
}
saving=false;
loading=false;
saveicon.addEventListener("click",()=>{
    savesound.play();
    if(!saving){
        savetext=document.getElementById("saved")
        savetext.style.display="inline"
        savechange=0.1
        saveopacity=0
        savetext.style.opacity=0
        saving=true
        saveappear=setInterval(()=>{
            saveopacity+=savechange
            savetext.style.opacity=saveopacity
            if(saveopacity>=1){
                savechange=-0.1
            }
            if(saveopacity<0){
                saving=false;
                savetext.style.display="none"
                clearInterval(saveappear)
            }
        },30)
    }
    tasks=document.getElementsByClassName("draggable")
    localStorage.setItem("TaskLength",tasks.length)
    for(i=0;i<tasks.length;i++){
        localStorage.setItem(`task${i}`,tasks[i].innerHTML.replace('<img src="Images/Trash.png" class="Trash" draggable="false">',""))
    }
})
loadicon.addEventListener("click",()=>{
    loadsound.play();
    if(!loading){
        loadtext=document.getElementById("loaded")
        loadtext.style.display="inline"
        loadchange=0.1
        loadopacity=0
        loadtext.style.opacity=0
        loading=true
        loadappear=setInterval(()=>{
            loadopacity+=loadchange
            loadtext.style.opacity=loadopacity
            if(loadopacity>=1){
                loadchange=-0.1
            }
            if(loadopacity<0){
                loading=false;
                loadtext.style.display="none"
                clearInterval(loadappear)
            }
        },30)
    }
    tasks=[...document.querySelectorAll(".draggable")]
    list=document.getElementById("TaskList")
    tasks.forEach(element => {
        list.removeChild(element);
    });
    for(i=0;i<localStorage.getItem("TaskLength");i++){
        Add(localStorage.getItem(`task${i}`))
    }
})